FORMAT: 1A
# Vitasnella - Tu al meglio
Documentazione API Tu al meglio 2017

#Group Codici fardello
## GET /loyalty/codes
Elenco dei codici fardello caricati dall'utente
+ Request (application/json)
    + Headers
        Authorization: Bearer <token>
+ Response 200 (application/json)
    + Attributes
        - data (Codes)

## POST /loyalty/codes
Caricamento di un codice fardello
+ Request (application/json)
    + Headers
        Authorization: Bearer <token>
    + Attributes
        - code: `MGHIG56` (string, required)
+ Response 200 (application/json)
    + Attributes
        - data (Codes)
+ Response 422 (application/json)
    + Attributes
        - data (ValidationError)


#Group Premi
## GET /loyalty/awards
Elenco dei premi disponibili
+ Request (application/json)
    + Headers
        Authorization: Bearer <token>
    + Attributes
        - threshold: `6` (string)
        - score: `6` (number)
+ Response 200 (application/json)
    + Attributes
        - data (array[Awards, Awards])


## GET /loyalty/awards/{id}
Dettaglio di un singolo premio
+ Request (application/json)
    + Headers
        Authorization: Bearer <token>
+ Parameters
    + id: `2` - Id del premio.
+ Response 200 (application/json)
    + Attributes
        - data (Awards)

## GET /loyalty/awards/request/{id}
Richiesta premio
+ Request (application/json)
    + Headers
        Authorization: Bearer <token>
+ Parameters
    + id: `2` - Id premio
+ Response 200 (application/json)
    + Attributes
        - data (Awards Request)
+ Response 422 (application/json)
  + Attributes
      - data (ValidationError)

#Group Soglie
## GET /loyalty/thresholds
Elenco delle soglie premio programma loyalty
+ Request (application/json)
    + Headers
        Authorization: Bearer <token>
+ Response 200 (application/json)
  + Attributes
    - data (array[Threshold, Threshold])

#Group Utente
## POST /users/register
Registrazione nuovo utente
+ Request (application/json)
    + Attributes (User Create)
+ Response 201 (application/json)
    + Attributes
        - data (User)
+ Response 422 (application/json)
    + Attributes
        - data (ValidationError)

## GET /users/me
Dettaglio utente loggato
+ Request (application/json)
    + Headers
        Authorization: Bearer <token>
+ Response 200 (application/json)
    + Attributes
        - data (User)
+ Response 422 (application/json)
    + Attributes
        - data (ValidationError)

## GET /users/{id}
Dettaglio utente
+ Request (application/json)
    + Headers
        Authorization: Bearer <token>
+ Parameters
    + id: `2` - Id
+ Response 200 (application/json)
    + Attributes
        - data (User)
+ Response 422 (application/json)
    + Attributes
        - data (ValidationError)

# Data Structures
## Codes (object)
- count: `20` (number, required) - Totale dei codici fardello caricati.

## Awards (object)
- id: `1` (number)
- title: `nome premio` (string)
- image: `http://placehold.it/600x600` (string)
- content: `lorem ipsum dolor sit amet lorem ipsum dolor sit amet` (string)
- excerpt: `lorem ipsum dolor` (string)
- threshold: `6` (string)
- score: `3` (number)
- partner: `nome partner` (string)
- additional_money: `20.00` (number)

## Awards full (object)
- Include Awards

## Awards Request (object)
- status: `success` (string)
- guid: `mhgd67` (string)

## ValidationError (object)
- status: `error` (string)
- error_code: `ERRCODE` (string)
- message: `error message string` (string)

## Threshold
- id: `1` (number)
- title: `nome soglia` (string)
- content: `lorem ipsum dolor sit amet lorem ipsum dolor sit amet` (string)

## UserBase
- first_name: `Maria` (string, required)
- last_name: `Rossi` (string, required)
- birthday: (array[Date Array], required)
- gender: `F` (string, required)
- phone: `3274595785` (string)
- address: `via Roma 120` (string, required)
- zip_code: `10100` (string, required)
- city: `Torino` (string, required)
- state: `TO` (string, required)
- email: `maria.rossi@test.com` (string, required)

## User Create (object)
- Include UserBase
- email_confirm: `maria.rossi@test.com` (string, required)
- password: `password` (string, required)
- password_confirm: `password` (string, required)
- terms: (array[User Terms], required)

## User (object)
- id: `1` (number)
- Include UserBase
- birthday_date: `1984-29-07` (string)
- terms: (array[User Terms], required)

## Date Array
- year: `1984` (number)
- month: `07` (number)
- day: `29` (number)

## User Terms
- 1: '0' (number)
- 2: `1` (number)
- 3: `1` (number)
- 4: `0` (number)
